WebAdvert.Web/Controllers/AccountsController.cs
using Amazon.Extensions.CognitoAuthentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAdvert.Web.Models.Accounts;
using Amazon.AspNetCore.Identity.Cognito;
using Amazon.CognitoIdentityProvider;
using Amazon.CognitoIdentityProvider.Model;
using Microsoft.Extensions.Configuration;
using System.Security.Cryptography;
using System.Net;

namespace WebAdvert.Web.Controllers
{
    public class AccountsController : Controller
    {
        private readonly SignInManager<CognitoUser> _signInManager;
        private readonly UserManager<CognitoUser> _userManager;
        private readonly AmazonCognitoIdentityProviderClient _cognitoIdnetityProvider;
        private readonly IConfiguration _configuration;
        private readonly CognitoUserPool _pool;
        public AccountsController(SignInManager<CognitoUser> signInManager,
                                  UserManager<CognitoUser> userMamager, 
                                  CognitoUserPool pool,
                                  AmazonCognitoIdentityProviderClient cognitoIdnetityProvider,
                                  IConfiguration configuration)
        {
            this._signInManager = signInManager;
            this._userManager = userMamager;
            this._pool = pool;
            this._cognitoIdnetityProvider = cognitoIdnetityProvider;
            this._configuration = configuration;
        }
        
        [HttpGet]
        public async Task<IActionResult> Signup()
        {
            var model = new SignupModel();
            return  View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Signup(SignupModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _pool.GetUser(model.Email);
                if(user.Status != null)
                {
                    ModelState.AddModelError("", "User with this email already exists");
                    return View(model);
                }
                //Attribute you selected as required in AWS Cognito
                user.Attributes.Add(CognitoAttribute.Name.ToString(), model.Email);
               
                var createdUser=  await _userManager.CreateAsync(user, model.Password);
                if (createdUser.Succeeded)
                {
                    RedirectToAction("Confirm");
                }
                if (createdUser.Errors != null && createdUser.Errors.Count() > 0)
                {
                    foreach(var error in createdUser.Errors)
                    {
                        ModelState.AddModelError(error.Code,error.Description);
                    }
                    
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Confirm()
        {
            var model = new ConfirmModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(ConfirmModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                if(user == null)
                {
                    ModelState.AddModelError("NotFound", "A user with the given email address not found");
                    return View(model);
                }
                //var result = await _userManager.ConfirmEmailAsync(user, model.Code); //Did not work for me so used the method below
                var result = await (_userManager as CognitoUserManager<CognitoUser>).ConfirmSignUpAsync(user, model.Code,true).ConfigureAwait(false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach(var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                    return View(model);
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Login()
        {
            var model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Privacy", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Email and password do not match");
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ForgetPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgetPassword(ForgetPassword password)
        {
            var user = await _userManager.FindByEmailAsync(password.Email);
            if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
            {
                ModelState.AddModelError("", "Confirmation of password is required.");
                return View();
            }
            var clientId = _configuration.GetValue<string>("aws:UserPoolClientId");
            var userPoolClientSecret = _configuration.GetValue<string>("aws:UserPoolClientSecret");
            ForgotPasswordRequest forgotPasswordRequest = new ForgotPasswordRequest();
            forgotPasswordRequest.ClientId = clientId;
            forgotPasswordRequest.Username = user.Username;
            forgotPasswordRequest.SecretHash = CreateToken($"{user.Username}{forgotPasswordRequest.ClientId}", userPoolClientSecret);
            ForgotPasswordResponse forgotPasswordResponse = await _cognitoIdnetityProvider.ForgotPasswordAsync(forgotPasswordRequest).ConfigureAwait(false);
            if (forgotPasswordResponse.HttpStatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("ForgotPasswordConfirmation", new { email = password.Email });
            }
            else
            {
                ModelState.AddModelError("", "Failed to reset the password.");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ForgotPasswordConfirmation(string email = null)
        {
            ForgetPasswordConfirmation forgetPasswordConfirmation = new ForgetPasswordConfirmation();
            if (email != null) 
            {
                forgetPasswordConfirmation.Email = email;
            }

            return View(forgetPasswordConfirmation);
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPasswordConfirmation(ForgetPasswordConfirmation forgetPasswordConfirmation)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var user = await _userManager.FindByEmailAsync(forgetPasswordConfirmation.Email);
            if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
            {
                ModelState.AddModelError("Email", "Problem occured with the email used");
                return View();
            }
            var clientId = _configuration.GetValue<string>("aws:UserPoolClientId");
            var userPoolClientSecret = _configuration.GetValue<string>("aws:UserPoolClientSecret");
            ConfirmForgotPasswordRequest confirmForgotPasswordRequest = new ConfirmForgotPasswordRequest();
            confirmForgotPasswordRequest.Username = user.Username;
            confirmForgotPasswordRequest.ClientId = clientId;
            confirmForgotPasswordRequest.Password = forgetPasswordConfirmation.Password;
            confirmForgotPasswordRequest.ConfirmationCode = forgetPasswordConfirmation.Code;
            confirmForgotPasswordRequest.SecretHash = CreateToken($"{user.Username}{confirmForgotPasswordRequest.ClientId}",
                                                                     userPoolClientSecret);
            ConfirmForgotPasswordResponse confirmForgotPasswordResponse = new ConfirmForgotPasswordResponse();
            string message = string.Empty;
            try
            {
                confirmForgotPasswordResponse = await _cognitoIdnetityProvider.ConfirmForgotPasswordAsync(confirmForgotPasswordRequest).ConfigureAwait(false);
            }
            catch (ExpiredCodeException ex)
            {
                message = ex.Message;
            }
            catch (InvalidPasswordException ex)
            {
                message = ex.Message;
            }
            catch (Amazon.CognitoIdentityProvider.Model.LimitExceededException ex)
            {
                message = ex.Message;
            }
            catch (UserNotFoundException ex)
            {
                message = ex.Message;
            }
            catch (UserNotConfirmedException ex)
            {
                message = ex.Message;
            }
            if (!string.IsNullOrWhiteSpace(message))
            {
                ModelState.AddModelError("", message);
            }
            if (confirmForgotPasswordResponse.HttpStatusCode == HttpStatusCode.OK)
            {
                ViewData["ResetPasswordSuccess"] = "Success in resetting user password";
            }
            return View();
        }

        private string CreateToken(string message, string secret)
        {
            secret = secret ?? "";
            var encoding = new System.Text.ASCIIEncoding();
            byte[] keyByte = encoding.GetBytes(secret);
            byte[] messageBytes = encoding.GetBytes(message);

WebAdvert.Web/Controllers/AdvertManagementController.cs
using AdvertApi.Models;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebAdvert.Web.Models.AdvertManagement;
using WebAdvert.Web.ServiceClient;
using WebAdvert.Web.Services;

namespace WebAdvert.Web.Controllers
{
    public class AdvertManagementController : Controller
    {
        public readonly IFileUploader _fileUploader;
        public readonly IAdvertApiClient _advertApiClient;
        public readonly IMapper _mapper;

        public AdvertManagementController(IFileUploader fileUploader,
                                          IAdvertApiClient advertApiClient,
                                          IMapper mapper)
        {
            this._fileUploader = fileUploader;
            this._advertApiClient = advertApiClient;
            this._mapper = mapper;
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateAdvertViewModel model = new CreateAdvertViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAdvertViewModel model, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                // _advertApiClient.Create
                //var createAdvertModel = _mapper.Map<CreateAdvertModel>(model);
                CreateAdvertModel createAdvertModel = new CreateAdvertModel()
                {
                    Description = model.Description,
                    Price = model.Price,
                    Title = model.Title
                };
                var apiCallResponse = await _advertApiClient.Create(createAdvertModel);

                var id = apiCallResponse.Id;

                var fileName = "";
                if(imageFile != null)
                {
                    fileName = !string.IsNullOrWhiteSpace(imageFile.FileName) ? Path.GetFileName(imageFile.FileName) : id;
                    var filePath = $"{id}/{fileName}";
                    try
                    {
                        using (var readStream = imageFile.OpenReadStream())
                        {
                            var result = await _fileUploader.UploadFileAsync(filePath, readStream)
                                                                 .ConfigureAwait(continueOnCapturedContext: false);
                            if (!result)
                                throw new Exception("Could not upload the image to file repository. Please see the logs for more detail.");
                        }
                        var confirmModel = new ConfimAdvertModel
                        {
                            Id = id,
                            FilePath = filePath,
                            Status = AdvertStatus.Active
                        };
                        
                        var conConfrim= await  _advertApiClient.Confirm(confirmModel);
                        if (!conConfrim)
                        {
                            throw new Exception(message: $"Cannot confirm advert of id = {id}");
                        }
                        return RedirectToAction("Index", controllerName: "Home");
                    }
                    catch(Exception ex)
                    {
                        var confirmModel = new ConfimAdvertModel
                        {
                            Id = id,
                            FilePath = filePath,
                            Status = AdvertStatus.Pending
                        };

                        var conConfrim = await _advertApiClient.Confirm(confirmModel);
                        Console.WriteLine(ex);
                    }
                }
            }
            return View();
        }
    }
}

WebAdvert.Web/Views/Shared/_AdvertDetail.cshtml
<div class="modal" tabindex="-1" role="dialog" id="detailsModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Advertisement Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="border-dark rounded advertDetailBox" id="advertDetailBox">
                    <div style="text-align:center;">
                        <img id="detailImage" class="box-shadow" />
                    </div>
                    <h4 id="detailTitle"></h4>
                    <p id="detailDesc"></p>
                    <p id="detailPrice"></p>
                </div>
            </div>
        </div>
    </div>
</div>

WebAdvert.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAdvert.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAdvert.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Signup">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Confirm">Confirm Email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdvertManagement" asp-action="Create">Add Item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAdvert.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>